development:
  adapter: postgresql
  encoding: unicode
  database: fishingusa_development
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

test:
  adapter: postgresql
  encoding: unicode
  database: fishingusa_test
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: fishingusa_production
  pool: 5
  username: michaelknueppel
  password: peculitcher88
